# Generated by Django 4.0.4 on 2022-05-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=60)),
                ('sender_email', models.EmailField(max_length=100)),
                ('sender_subject', models.CharField(max_length=60)),
                ('sender_message', models.TextField()),
            ],
        ),
    ]
