# Generated by Django 4.0.4 on 2022-05-12 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_category', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, upload_to='category_pics')),
                ('slug', models.SlugField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_date',),
                'unique_together': {('label_category',)},
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_city', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_country', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_marque', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=250)),
                ('slug', models.SlugField()),
                ('prices', models.FloatField(default=0.0)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('size', models.CharField(choices=[('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default='L', max_length=50)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('date_add', models.DateTimeField(auto_now=True)),
                ('update_on', models.DateTimeField(auto_now=True)),
                ('image1', models.ImageField(upload_to='product_img')),
                ('image2', models.ImageField(blank=True, upload_to='product_img')),
                ('image3', models.ImageField(blank=True, upload_to='product_img')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_shop.category')),
                ('marque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_shop.marque')),
            ],
            options={
                'ordering': ('-date_add',),
                'unique_together': {('label',)},
            },
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ManyToManyField(blank=True, to='admin_shop.product')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(blank=True, max_length=250)),
                ('facebook_urls', models.URLField(blank=True)),
                ('twitter_urls', models.URLField(blank=True)),
                ('linkded_urls', models.URLField(blank=True)),
                ('city', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='admin_shop.city')),
                ('country', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='admin_shop.country')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='name_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_shop.country'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_frais', models.PositiveBigIntegerField(default=0)),
                ('products', models.ManyToManyField(blank=True, to='admin_shop.product')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
