# Generated by Django 4.0.4 on 2022-05-05 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_Categorie', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_city', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_count', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_marque', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=250)),
                ('Prices', models.FloatField(default=0.0)),
                ('description', models.TextField(blank=True, max_length=10000)),
                ('size', models.CharField(choices=[('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default='L', max_length=50)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('date_add', models.DateTimeField(auto_now=True)),
                ('image1', models.ImageField(blank=True, upload_to=True)),
                ('image2', models.ImageField(blank=True, upload_to=True)),
                ('image3', models.ImageField(blank=True, upload_to=True)),
                ('label_Categorie', models.ForeignKey(default='Vetement', on_delete=django.db.models.deletion.CASCADE, to='admin_shop.categorie')),
                ('marque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_shop.marque')),
            ],
        ),
        migrations.CreateModel(
            name='WhistListCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod', models.ManyToManyField(to='admin_shop.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('fistname', models.CharField(max_length=200)),
                ('Address', models.CharField(max_length=250)),
                ('name_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_shop.city')),
                ('name_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_shop.country')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='name_count',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_shop.country'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_cart', models.ManyToManyField(to='admin_shop.produit')),
            ],
        ),
    ]
