# Generated by Django 4.0.4 on 2022-05-03 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_city', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_marque', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=250)),
                ('sexe', models.CharField(choices=[('max', 'Masculin'), ('fem', 'Feminin')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WhistListCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_prod', models.CharField(max_length=250)),
                ('Prices_prod', models.FloatField()),
                ('description_prod', models.TextField(max_length=10000)),
                ('size_prod', models.CharField(choices=[('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=20)),
                ('quantity_prod', models.PositiveIntegerField()),
                ('image1', models.ImageField(null=True, upload_to='')),
                ('image2', models.ImageField(null=True, upload_to='')),
                ('image3', models.ImageField(null=True, upload_to='')),
                ('label_marque_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_shop.marque')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_count', models.CharField(max_length=200)),
                ('city_of_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_shop.city')),
            ],
        ),
    ]
