# Generated by Django 4.0.4 on 2022-05-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
