# Generated by Django 4.0.4 on 2022-05-04 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_shop', '0002_remove_country_city_of_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='label',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fistname',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
