# Generated by Django 4.0.4 on 2022-05-05 13:31

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_shop', '0002_alter_produit_label_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='image1',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/media/photos'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='produit',
            name='image2',
            field=models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='/media/photos'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='produit',
            name='image3',
            field=models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='/media/photos'), upload_to=''),
        ),
    ]
