# Generated by Django 4.0.4 on 2022-05-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_shop', '0003_alter_produit_image1_alter_produit_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='facebook_urls',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkded_urls',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter_urls',
            field=models.URLField(blank=True),
        ),
    ]
