# Generated by Django 4.0.4 on 2022-05-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_shop', '0005_categorie_image_alter_produit_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='Total_frais',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
